name: Test Push Trigger

# Déclenche à chaque push sur la branche main
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print push info
        run: |
          echo "Workflow déclenché !"
          echo "Branche : ${{ github.ref }}"
          echo "Utilisateur : ${{ github.actor }}"
